# Generated by Django 4.2.4 on 2023-08-15 13:07

import Mailer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('mailCount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.FileField(blank=True, null=True, upload_to=Mailer.models.generate_random_filename)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
