# Generated by Django 4.2.4 on 2023-08-19 16:41

import Mailer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailer', '0002_mail_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mail',
            name='logFile',
            field=models.FileField(blank=True, null=True, upload_to=Mailer.models.generate_logfile_name),
        ),
        migrations.AddField(
            model_name='mail',
            name='success',
            field=models.IntegerField(default=0),
        ),
    ]
