# Generated by Django 4.2.4 on 2023-08-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailer', '0003_mail_failed_mail_logfile_mail_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='senderId',
            field=models.CharField(default='Rendezvous IIT Delhi <noreply@rendezvousiitd.com>'),
        ),
    ]
