# Generated by Django 4.2.4 on 2023-08-21 07:42

import Mailer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailer', '0004_mail_senderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=Mailer.models.generate_attachment_name),
        ),
    ]
