# Generated by Django 4.2.4 on 2023-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pronite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='exhaust_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
