# Generated by Django 4.2.4 on 2023-09-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pronite', '0002_slot_exhaust_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='eligibility',
            field=models.CharField(choices=[('E', 'External'), ('S', 'IITD Students'), ('F', 'IITD Faculty and Staff'), ('X', 'Sponsors')], default='E', max_length=1),
        ),
    ]
