# Generated by Django 4.2.4 on 2023-09-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pronite', '0003_slot_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='eligibility',
            field=models.CharField(choices=[('E', 'External'), ('T', 'Team'), ('S', 'IITD Students'), ('F', 'IITD Faculty and Staff'), ('X', 'Others')], default='E', max_length=1),
        ),
    ]
