# Generated by Django 4.2.4 on 2023-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pronite', '0004_alter_slot_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='pronite',
            field=models.CharField(choices=[('S', 'Spectrum'), ('K', 'Kaleidoscope'), ('M', 'Melange'), ('D', 'Dhoom')], max_length=1),
        ),
    ]
