# Generated by Django 4.2.4 on 2023-10-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pronite', '0005_alter_slot_pronite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronite', models.CharField(choices=[('S', 'Spectrum'), ('K', 'Kaleidoscope'), ('M', 'Melange'), ('D', 'Dhoom')], max_length=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='admission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
