# Generated by Django 4.2.4 on 2023-10-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pronite', '0006_scanningschedule_booking_admission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanningschedule',
            name='admissions',
            field=models.IntegerField(default=0),
        ),
    ]
