# Generated by Django 4.2.4 on 2023-10-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pronite', '0008_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pass_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
