# Generated by Django 4.2.4 on 2023-08-21 21:16

import Users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college_id", models.CharField(max_length=10, unique=True)),
                ("college_name", models.CharField(max_length=200)),
                ("college_city", models.CharField(max_length=100)),
                ("college_state", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rdv_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mobile_number", models.CharField(max_length=10)),
                (
                    "profile_photo",
                    models.ImageField(upload_to=Users.models.upload_path),
                ),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("is_ca", models.BooleanField(default=False)),
                ("ca_id", models.CharField(blank=True, max_length=10, null=True)),
                ("instagram_link", models.URLField(blank=True, null=True)),
                ("linkedin_link", models.URLField(blank=True, null=True)),
                (
                    "college_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.college"
                    ),
                ),
            ],
        ),
    ]
