# Generated by Django 4.2.4 on 2023-08-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college_id',
            field=models.IntegerField(),
        ),
    ]
