# Generated by Django 4.2.4 on 2023-09-24 12:21

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_profile_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="images/default.jpg", upload_to=Users.models.upload_path
            ),
        ),
    ]
