# Generated by Django 4.2.4 on 2023-09-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_profile_mobile_number_and_more'),
        ('Users', '0006_profile_user_category'),
    ]

    operations = [
    ]
