# Generated by Django 4.2.4 on 2023-09-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_merge_20230924_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_category',
            field=models.CharField(choices=[('E', 'External'), ('T', 'Team'), ('S', 'IITD Student'), ('F', 'IITD Faculty/Staff'), ('X', 'Others')], default='E', max_length=1),
        ),
    ]
