# Generated by Django 4.2.4 on 2023-10-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_profile_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='BlockedFromPronite',
            field=models.BooleanField(default=False),
        ),
    ]
