# Generated by Django 4.2.4 on 2023-10-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_profile_college_name'),
        ('Users', '0009_profile_blockedfrompronite'),
    ]

    operations = [
    ]
