# Generated by Django 4.2.4 on 2023-09-24 12:21

import Events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "poster",
                    models.ImageField(
                        blank=True, null=True, upload_to=Events.models.upload_path
                    ),
                ),
                ("description", models.TextField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("application_deadline", models.DateField()),
                ("event_date_time", models.DateTimeField()),
                ("team_size", models.IntegerField()),
                ("registration_link", models.URLField()),
                ("rulebook_link", models.URLField()),
                ("tags", models.ManyToManyField(to="Events.tag")),
            ],
        ),
    ]
