# Generated by Django 4.2.4 on 2023-09-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='team_size',
            field=models.CharField(max_length=20),
        ),
    ]
