# Generated by Django 4.2.4 on 2023-09-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prizes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
