# Generated by Django 4.2.4 on 2023-09-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_event_prizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='mode',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Competitive', 'Competitive'), ('Non-Competitive', 'Non-Competitive')], default='Competitive', max_length=40),
            preserve_default=False,
        ),
    ]
