# Generated by Django 4.2.4 on 2023-08-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CAP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("points", models.IntegerField()),
                ("deadline", models.DateTimeField()),
                ("multiple_uploads_allowed", models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name="submission",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="CAP.task"
            ),
        ),
    ]
